import { Purchase, PaymentRecord } from '../types';

export const INITIAL_PURCHASES: Purchase[] = [
  {
    id: 'compra-freezer-ipda',
    description: 'Freezer IPDA Rio Formoso',
    category: 'igreja',
    purchaseDate: '2026-09-12',
    totalAmountInCents: 300000, // R$ 3.000,00
    installmentsCount: 10,
    installmentAmountInCents: 30000, // R$ 300,00
    firstDueDate: '2026-09-10',
    notes: 'Freezer adquirido para a cantina e eventos da igreja.',
    createdAt: '2026-09-12T10:00:00.000Z',
    updatedAt: '2026-09-14T15:00:00.000Z',
    installments: [
      {
        id: 'inst-freezer-1',
        purchaseId: 'compra-freezer-ipda',
        number: 1,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2026-09-10',
        paid: true,
        paidAt: '2026-09-14',
        paymentNote: 'Antecipação de parcela',
        paymentRecordId: 'pag-freezer-1',
      },
      {
        id: 'inst-freezer-2',
        purchaseId: 'compra-freezer-ipda',
        number: 2,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2026-09-14',
        paid: true,
        paidAt: '2026-09-14',
        paymentNote: 'Antecipação de parcela',
        paymentRecordId: 'pag-freezer-2',
      },
      {
        id: 'inst-freezer-3',
        purchaseId: 'compra-freezer-ipda',
        number: 3,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2026-10-10',
        paid: false,
      },
      {
        id: 'inst-freezer-4',
        purchaseId: 'compra-freezer-ipda',
        number: 4,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2026-11-10',
        paid: false,
      },
      {
        id: 'inst-freezer-5',
        purchaseId: 'compra-freezer-ipda',
        number: 5,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2026-12-10',
        paid: false,
      },
      {
        id: 'inst-freezer-6',
        purchaseId: 'compra-freezer-ipda',
        number: 6,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2027-01-10',
        paid: false,
      },
      {
        id: 'inst-freezer-7',
        purchaseId: 'compra-freezer-ipda',
        number: 7,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2027-02-10',
        paid: false,
      },
      {
        id: 'inst-freezer-8',
        purchaseId: 'compra-freezer-ipda',
        number: 8,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2027-03-10',
        paid: false,
      },
      {
        id: 'inst-freezer-9',
        purchaseId: 'compra-freezer-ipda',
        number: 9,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2027-04-10',
        paid: false,
      },
      {
        id: 'inst-freezer-10',
        purchaseId: 'compra-freezer-ipda',
        number: 10,
        totalInstallments: 10,
        amountInCents: 30000,
        dueDate: '2027-05-10',
        paid: false,
      },
    ],
  },
  {
    id: 'compra-lembrancinhas',
    description: 'Lembrancinhas da festividade',
    category: 'igreja',
    purchaseDate: '2026-09-10',
    totalAmountInCents: 68995, // R$ 689,95 (2x de R$ 344,98)
    installmentsCount: 2,
    installmentAmountInCents: 34498, // R$ 344,98
    firstDueDate: '2026-10-10',
    notes: 'Lembrancinhas para a festividade da congregação (2x R$ 344,98).',
    createdAt: '2026-09-10T10:00:00.000Z',
    updatedAt: '2026-09-10T10:00:00.000Z',
    installments: [
      {
        id: 'inst-lembrancinhas-1',
        purchaseId: 'compra-lembrancinhas',
        number: 1,
        totalInstallments: 2,
        amountInCents: 34498, // R$ 344,98
        dueDate: '2026-10-10',
        paid: false,
      },
      {
        id: 'inst-lembrancinhas-2',
        purchaseId: 'compra-lembrancinhas',
        number: 2,
        totalInstallments: 2,
        amountInCents: 34497, // R$ 344,97 (ajuste do centavo para totalizar R$ 689,95)
        dueDate: '2026-11-10',
        paid: false,
      },
    ],
  },
  {
    id: 'compra-tablet-som',
    description: 'Tablet da igreja / mesa de som digital',
    category: 'igreja',
    purchaseDate: '2026-08-10',
    totalAmountInCents: 172720, // R$ 1.727,20
    installmentsCount: 5,
    installmentAmountInCents: 34544, // R$ 345,44 (5 * 34544 = 172720)
    firstDueDate: '2026-08-10',
    notes: 'Tablet para controle da mesa de som digital nos cultos.',
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-09-10T10:00:00.000Z',
    installments: [
      {
        id: 'inst-tablet-1',
        purchaseId: 'compra-tablet-som',
        number: 1,
        totalInstallments: 5,
        amountInCents: 34544,
        dueDate: '2026-08-10',
        paid: true,
        paidAt: '2026-08-10',
        paymentNote: '1ª parcela paga',
        paymentRecordId: 'pag-tablet-1',
      },
      {
        id: 'inst-tablet-2',
        purchaseId: 'compra-tablet-som',
        number: 2,
        totalInstallments: 5,
        amountInCents: 34544,
        dueDate: '2026-09-10',
        paid: true,
        paidAt: '2026-09-10',
        paymentNote: '2ª parcela paga',
        paymentRecordId: 'pag-tablet-2',
      },
      {
        id: 'inst-tablet-3',
        purchaseId: 'compra-tablet-som',
        number: 3,
        totalInstallments: 5,
        amountInCents: 34544,
        dueDate: '2026-10-10',
        paid: false,
      },
      {
        id: 'inst-tablet-4',
        purchaseId: 'compra-tablet-som',
        number: 4,
        totalInstallments: 5,
        amountInCents: 34544,
        dueDate: '2026-11-10',
        paid: false,
      },
      {
        id: 'inst-tablet-5',
        purchaseId: 'compra-tablet-som',
        number: 5,
        totalInstallments: 5,
        amountInCents: 34544,
        dueDate: '2026-12-10',
        paid: false,
      },
    ],
  },
  {
    id: 'compra-aparelho-carro',
    description: 'Aparelho de carro',
    category: 'particular',
    purchaseDate: '2026-08-10',
    totalAmountInCents: 240900, // R$ 2.409,00
    installmentsCount: 6,
    installmentAmountInCents: 40150, // R$ 401,50 (6 * 40150 = 240900)
    firstDueDate: '2026-09-10',
    notes: 'Compra particular do pastor parcelada no cartão.',
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-09-10T10:00:00.000Z',
    installments: [
      {
        id: 'inst-carro-1',
        purchaseId: 'compra-aparelho-carro',
        number: 1,
        totalInstallments: 6,
        amountInCents: 40150,
        dueDate: '2026-09-10',
        paid: true,
        paidAt: '2026-09-10',
        paymentNote: '1ª parcela paga em dia',
        paymentRecordId: 'pag-carro-1',
      },
      {
        id: 'inst-carro-2',
        purchaseId: 'compra-aparelho-carro',
        number: 2,
        totalInstallments: 6,
        amountInCents: 40150,
        dueDate: '2026-10-10',
        paid: false,
      },
      {
        id: 'inst-carro-3',
        purchaseId: 'compra-aparelho-carro',
        number: 3,
        totalInstallments: 6,
        amountInCents: 40150,
        dueDate: '2026-11-10',
        paid: false,
      },
      {
        id: 'inst-carro-4',
        purchaseId: 'compra-aparelho-carro',
        number: 4,
        totalInstallments: 6,
        amountInCents: 40150,
        dueDate: '2026-12-10',
        paid: false,
      },
      {
        id: 'inst-carro-5',
        purchaseId: 'compra-aparelho-carro',
        number: 5,
        totalInstallments: 6,
        amountInCents: 40150,
        dueDate: '2027-01-10',
        paid: false,
      },
      {
        id: 'inst-carro-6',
        purchaseId: 'compra-aparelho-carro',
        number: 6,
        totalInstallments: 6,
        amountInCents: 40150,
        dueDate: '2027-02-10',
        paid: false,
      },
    ],
  },
];

export const INITIAL_PAYMENT_RECORDS: PaymentRecord[] = [
  {
    id: 'pag-freezer-1',
    purchaseId: 'compra-freezer-ipda',
    installmentId: 'inst-freezer-1',
    installmentNumber: 1,
    totalInstallments: 10,
    amountInCents: 30000,
    paymentDate: '2026-09-14',
    purchaseDescription: 'Freezer IPDA Rio Formoso',
    category: 'igreja',
    note: 'Antecipação de parcela',
    recordedAt: '2026-09-14T14:30:00.000Z',
  },
  {
    id: 'pag-freezer-2',
    purchaseId: 'compra-freezer-ipda',
    installmentId: 'inst-freezer-2',
    installmentNumber: 2,
    totalInstallments: 10,
    amountInCents: 30000,
    paymentDate: '2026-09-14',
    purchaseDescription: 'Freezer IPDA Rio Formoso',
    category: 'igreja',
    note: 'Antecipação de parcela',
    recordedAt: '2026-09-14T14:31:00.000Z',
  },
  {
    id: 'pag-tablet-1',
    purchaseId: 'compra-tablet-som',
    installmentId: 'inst-tablet-1',
    installmentNumber: 1,
    totalInstallments: 5,
    amountInCents: 34544,
    paymentDate: '2026-08-10',
    purchaseDescription: 'Tablet da igreja / mesa de som digital',
    category: 'igreja',
    note: '1ª parcela paga',
    recordedAt: '2026-08-10T12:00:00.000Z',
  },
  {
    id: 'pag-tablet-2',
    purchaseId: 'compra-tablet-som',
    installmentId: 'inst-tablet-2',
    installmentNumber: 2,
    totalInstallments: 5,
    amountInCents: 34544,
    paymentDate: '2026-09-10',
    purchaseDescription: 'Tablet da igreja / mesa de som digital',
    category: 'igreja',
    note: '2ª parcela paga',
    recordedAt: '2026-09-10T11:00:00.000Z',
  },
  {
    id: 'pag-carro-1',
    purchaseId: 'compra-aparelho-carro',
    installmentId: 'inst-carro-1',
    installmentNumber: 1,
    totalInstallments: 6,
    amountInCents: 40150,
    paymentDate: '2026-09-10',
    purchaseDescription: 'Aparelho de carro',
    category: 'particular',
    note: '1ª parcela paga em dia',
    recordedAt: '2026-09-10T15:00:00.000Z',
  },
];
